---
title: "ST_558_HW_3"
author: "Stephanie Shuai, Jiayin Liu"
format: html
editor: visual
---

#Task 1
library(tidyverse)
library(readr)
library(dplyr)
#1
# "../MyData.csv"


#2
# R is good for all following task:
# Read raw data in or connect to a database
# Manipulate data as need
#   Subset
#   Create new variables
# Summarize data to create meaningful insights
# Modeling data to make inference or predict outcomes
# Communicate our results via dashboards, documents, model files, etc.


#3
# Git is a version control software
# Github is an online hosting service for Git-based projects

#4
# First, a tibble prints more nicely. It only shows the first few rows and columns that fit on the screen, 
# while a data.frame may print too much.

# Second, a tibble is stricter and more predictable. 
# For example, it does not automatically change variable types or names as much as a 
# traditional data.frame may.

#5
iris |>
  as_tibble() |>
  select(starts_with("Petal"), Species) |>
  filter(Petal.Length < 1.55) |>
  arrange(Species)

#6
# long format: each row consists of one observation and each column one variable 
# wide format data: we may have more than one observation in a given row.


#Task 2
glass_dt<-read_delim('https://www4.stat.ncsu.edu/online/datasets/glass.data',delim=",",
           col_names=c('Id','RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','Type_of_glass'))
#2.
glass_dt2<-glass_dt %>% mutate(
  Type_of_glass = factor(
    Type_of_glass,
    levels = c(1, 2, 3, 4, 5, 6, 7),
    labels = c(
      "building_windows_float_processed",
      "building_windows_non_float_processed",
      "vehicle_windows_float_processed",
      "vehicle_windows_non_float_processed",
      "containers",
      "tableware",
      "headlamps"
    )
  )
)

#3
glass_dt3<-glass_dt2 %>% 
  filter(Fe < 0.2&Type_of_glass %in% c("tableware", "headlamps"))

#Task 2
#1
yeast_url <- "https://www4.stat.ncsu.edu/~online/datasets/yeast.data"

col_names <- c("seq_name", "mcg", "gvh", "alm", "mit", "erl",
               "pox", "vac", "nuc", "class")

yeast <- read_table( file = yeast_url,col_names = col_names)

# Print out the tibble (is this correct?)
yeast

#2
yeast_2 <- yeast %>%
  select(-seq_name, -nuc)

yeast_2

# 3
yeast3 <- yeast_2 %>%
  group_by(class) %>%
  mutate( across(where(is.numeric),mean,.names = "mean_{.col}" ),
          across(where(is.numeric),median,.names='median_{.col}'))

yeast3

## Question 3

#1.  Read in the White Wine Excel file

library(readxl)
white_wine <- read_excel("~/Desktop/ST 558/ST 558 HW3/white-wine.xlsx", sheet = 1)
white_wine 


#2.  Rename columns using Sheet 2

new_names <- read_excel("~/Desktop/ST 558/ST 558 HW3/white-wine.xlsx", sheet = 2)

colnames(white_wine) <- new_names[[1]]



#3.  Add type column for white wine

library(dplyr)

white_wine <- white_wine |> 
                mutate(type = "white")



#4.  Read in the Red Wine CSV


library(readr)
red_wine <- read_delim("~/Desktop/ST 558/ST 558 HW3/red-wine.csv", 
                       delim = ";",
                       show_col_types = FALSE)
colnames(red_wine) <- new_names[[1]]

red_wine <- red_wine |> 
              mutate(type = "red")


#5.  Combine both datasets


wine <- dplyr::bind_rows(white_wine, red_wine)



#6-9. Combined data object to filter the data

wine |> 
  # Filter high quality and reasonable alcohol 
  filter(quality > 6.5 & alcohol < 132) |>
  # Sort highest quality to lowest
  arrange(desc(quality)) |>
  # Select acid columns, alcohol, type, quality
  dplyr::select(contains("acid"), alcohol, type, quality) |>
  # Add mean and sd of alcohol for each quality level
  group_by(quality) |>
  mutate(
    mean_alcohol = mean(alcohol),
    sd_alcohol = sd(alcohol)
  )


## Question 4

#1.  Connect to the database and list all tables

install.packages("RSQLite")


library(DBI)

con <- dbConnect(RSQLite::SQLite(), "~/Desktop/ST 558/ST 558 HW3/lahman.db")

dbListTables(con)


#2.  Using the tbl() function and dplyr to return all of the data

library(dbplyr)

tbl(con, "Teams") |>
  filter(yearID == 2015 ) |>
  collect()


#3.  Using the sql() function

tbl(con, sql( "SELECT * 
                FROM Teams
              WHERE yearID == 2015")) |>
  collect()


#4.  Inducted players only

hof <- tbl(con, sql("
          SELECT playerID, yearID, category
          From HallOfFame 
          WHERE inducted = 'Y'
          ")) |>
        collect()
hof


#5.  Add nameFirst and nameLast from People

hof_names <- tbl(con, sql("
              SELECT h.playerID, h.yearID, h.category, p.nameFirst, p.nameLast
              From HallOfFame h
              JOIN People p ON h.playerID = p.playerID
              WHERE h.inducted = 'Y'
              ")) |>
            collect()
hof_names


#6.  Managers win/loss records and win percentage

managers <- tbl(con, "Managers") |>
                select(playerID, G, W, L) |>
                group_by(playerID) |>
                summarize(G_managed = sum(G, na.rm = TRUE),
                  Total_W = sum(W, na.rm = TRUE),
                  Total_L = sum(L, na.rm = TRUE)) |>
                collect() |>
                mutate(win_pct = Total_W/G_managed) |>
                arrange(desc(win_pct))
managers


#7.  Join two previous table

hof_names |>
  inner_join(managers, by = "playerID")

